version: '3.8'

services: 
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./Dockerfile
    image: wedive/api
    ports: 
      - "4000:4000"
    restart: unless-stopped
    env_file: 
      - aws-secret.env
      - db-config.env
      - s3-config.env
    networks: 
      - api-network
      - mongo-network
      
networks:
  api-network:
    driver: bridge
    name: api-network

  mongo-network:
    external: true