version: '3.8'

services: 
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./Dockerfile
    image: wedive/api
    ports: 
      - "4000:4000"
    restart: unless-stopped
    networks: 
      - api-network
      - mongodb-network
      
networks:
  api-network:
    driver: bridge
    name: api-network

  mongodb-network:
    external: true