version: '3.8'

services: 
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports: 
      - "4000:4000"
    restart: unless-stopped
    environment:
      - DB_PATH=mongodb://mongodb:27017
    networks: 
      - wedive-mongodb_default
      - default

  
networks:
  wedive-mongodb_default:
    external: true