version: '3.8'

services: 
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports: 
      - "4000:4000"
    restart: unless-stopped
    env_file: 
      - wedive-secret/api-secret.env
      - wedive-secret/api-config.env
    networks: 
      - wedive-mongodb_default
      - default
  
networks:
  wedive-mongodb_default:
    external: true